dashboard/models.py

Enforce \ge 0 hours and \ge 0 clubs

---

roster/views.py

Previously, if a student had a unit they could then drop it and loose access. If this is done by accident or a student changes their mind, they shouldn't have to re-request (considering it had already been approved), as long as they are under the unit limit.
Addresses: #14 
* Adds a new auto-approval condition that addresses the 'unit previously dropped' case

Allow a student to 'undrop' units

---

Dockerfile.dev
README.mkd
wikihaxx/mdx/otis.py

Adds a quick fix to #10 by bringing in the description.
Also adds a Dockerfile + updates to `README.mkd` to make development setup faster.

Fixes #10, Adds Docker

---

.github/workflows/main.yml
lint.sh
poetry.lock
pyproject.toml
requirements.txt

Make django storages optional

---

.gitignore
dashboard/levelsys.py
dashboard/migrations/0030_rename_achievementcode_achievement.py
dashboard/tests.py

Personally I like decimals better, and the text is a bit too close to the emoji anyways
Maybe we could add a display setting for this.

add float level meters

---

arch/templates/arch/hint_list.html

(Describe what kind of changes you made here:
e.g. enhancement or feature update, bug fix,
typos or copy edits, etc.)

Change Add Hint button color to green

---

markets/templates/markets/market_list.html

Linked the market discussion channel to the market page. Now it's much easier to find and use the channel. At least now guys, discuss markets (and not other stuff in this channel)
Describe what kind of changes you made here:
very small enhancement
If you're an OTIS student, include your OTIS-WEB username or student ID number
Lasitha Vishwajith Jayasinghe

Try and promote discussion on markets

---

markets/templates/markets/market_list.html
markets/templates/markets/market_spades.html
markets/tests.py
markets/urls.py
markets/views.py

Feature: Market spade page (#75 ) 
Student ID:  819

Add market spades page and update links

---

payments/views.py

Suppress `webhook` errors in testing

---

dashboard/views.py
suggestions/templates/suggestions/problemsuggestion_form.html
suggestions/templates/suggestions/suggestion_queue_list.html
suggestions/urls.py
suggestions/views.py

Fixes #153 
This adds a basic suggestion queue based off the pset queue.
Unacknowledged suggestions are only visible to staff and the submitter.

Create Suggestion Queue

---

env

Recomment CERT_HASH_KEY

---

rpg/templates/rpg/diamond_list.html
rpg/views.py

For some reason the last commit of the previous pr wasn't added, but https://github.com/vEnhance/otis-web/commit/6b079d53c35fe3dfec27ec8cecb3dc52ee3a6d1e is the only commit that matters here.
This converts the expiration from daily at UTC to when you gain a diamond, which is a lot cleaner in my mind and discourages hoarding links for extended periods of time still.
It also brightens up the colors a bit, and changes the wording a bit

Dropped Changes

---

rpg/templates/rpg/stats.html
rpg/views.py

Somehow broke #168 as a pr, so this is a duplicate.
There probably is a better replacement than a sob emote, feel free to suggest alternatives :).

Increase Warning Message Verbosity

---

suggestions/tests.py
suggestions/views.py

Suggestion Tests

---

arch/templates/arch/hint_form.html
suggestions/templates/suggestions/problemsuggestion_form.html

Fixes #160 
Code is a bit awkward to interact with `generic_form`

Instant Tex for Hints

---

roster/templates/roster/currshow.html
roster/tests.py
roster/views.py

This does not fix the roster/views.py issue, since it only bumps it up to 92%. However, I've determined that the remaining lines that are missing seem difficult or even impossible to do properly so I don't feel like doing them for the new future.

[92%] Roster Tests Partial Progress

---

roster/tests.py

This gets roster coverage up to 95% through stupid code.
Fixes #134

Increase roster coverage to 95%

---

roster/templates/roster/gigachart.html
roster/views.py

Fixes #112 
This adds a table for html based off DataTables, with the extensions of column reordering + freeze column + freeze header. Feel free to change extensions used or something.

Add Gigachart Table 

---

roster/tests.py
roster/views.py

Fixes #203 
Also attempts to streamline inquiry logic through moving logic to a separate function while staying the same afaik, tests still pass,
It might be best to review this commit by commit.

Unit Petition Logic Changes

---

core/templates/core/unitgroup_list.html
core/views.py

Work on #206 but doesn't handle individual Unit checkmarks and only UnitGroup ones.

Catalog Checkmarks

---

dashboard/templates/dashboard/certify.html
dashboard/views.py

- Mention that hours count is self reported
- Mention total number of completed units
- Oxford Comma

Minor Changes to the certificate

---

rpg/views.py

Fixes #241, close if decided to not allow.

Dotted Moment

---

core/templates/core/unit_list.html
core/views.py

Grey for locked, blue for working on.

Color Other Catalogue Types

---

roster/tests.py
roster/views.py

Fixes #313. Adds some more comments as well.

Auto-accept K Units

---

core/tests.py
core/views.py
fixtures/all.json

Secret units don't show up in the catalog even if they're unlocked, this fixes that.
Fixes https://github.com/vEnhance/otis-web/issues/210

Unlocked secret units in catalog

---

opal/templates/opal/instructions_solvers.html

The title says Author instructions

fix(opal): Change title of rules page

---

roster/tests.py

Describe what kind of changes you made here:
e.g. enhancement or feature update, bug fix, typos or copy edits, etc.
If you're an OTIS student, include your OTIS-WEB username or student ID number
(whichever you prefer) so I can grant you the spades bounty as well.

fix: what in the typo

---

arch/templates/arch/hint_detail.html
roster/templates/roster/invoice.html
rpg/templates/rpg/diamond_solution.html

Describe what kind of changes you made here:
I added a little bit of css to make the long text wrap.
Please let me know if (when) there are problems.
Username: Kempu33334
ID: 2312

polish: Added word wrapping for long urls, better UI/visual quality on small screens.

---

arch/templates/arch/hint_detail.html

Solves https://github.com/vEnhance/otis-web/issues/332.
I added JavaScript code to the hint_detail.html so that when the escape key is pressed, it navigates back to the list of hints page.
(It works on my end, but please let me know if it doesn't work so I can fix it.)
Username: Kempu33334
ID: 2312

feat: Update hint_detail.html

---

core/templates/core/unit_list.html
core/templates/core/unit_search_form.html
dashboard/templates/dashboard/uploads.html

Added #288 on Compact Catalogue and issue #290 on Gating Manual Unit Upload.
_OTIS Username: Kempu33334
ID: 2312_

feat: Added issue #288 and issue #290

---

roster/utils.py

Fixed issue #350.
_Username: Kempu33334
ID: 2312_

fix: Fixed issue #350

---

roster/models.py
roster/templates/roster/inquiry.html
roster/tests.py
roster/urls.py
roster/views.py

added in #344 on petition canceling
_Username: Kempu33334
ID: 2312_

feat: Allow cancel petitions (closes #344)
